import Config

if config_env() == :prod do
  # SQLite Config
  database_path = System.get_env("DATABASE_PATH") || "/app/data/viking.db"
  
  config :app_api, AppApi.Repo,
    database: database_path,
    pool_size: String.to_integer(System.get_env("POOL_SIZE") || "5")

  # Secret Key
  secret_key_base =
    System.get_env("SECRET_KEY_BASE") ||
      raise """
      environment variable SECRET_KEY_BASE is missing.
      This should be auto-generated by the entrypoint script.
      """

  host = System.get_env("PHX_HOST") || "localhost"
  port = String.to_integer(System.get_env("PORT") || "4000")

  config :app_api, AppApiWeb.Endpoint,
    url: [host: host, port: 443, scheme: "https"],
    http: [
      ip: {0, 0, 0, 0, 0, 0, 0, 0},
      port: port
    ],
    secret_key_base: secret_key_base,
    server: true,
    # ✅ WEBSOCKET ORIGIN CHECK FIX
    check_origin: false  # Erlaubt alle Origins (Home Lab sicher)

  config :swoosh, api_client: Swoosh.ApiClient.Finch, finch_name: AppApi.Finch
end
